### ISSUE TITLE
Using the version in the examples fails

### ISSUE THREAD

**Issue by afonsojramos** [uraimo/run-on-arch-action#73]
Using v2 instead of specifying the version gives an error.
```
Error: Unable to resolve action `uraimo/run-on-arch-action@v2`, unable to find version `v2`
```

Example [here](https://github.com/afonsojramos/discrakt/runs/5673947505?check_suite_focus=true).

**Comment by uraimo** [comment]
Fixed in v2.1.2, let me know if it's fixed for you, thanks.

**Comment by afonsojramos** [comment]
This fixed it, yes! However, it is still not working for my workflow, can you maybe help? I was [trying to install Rust](https://github.com/afonsojramos/discrakt/runs/5678115833?check_suite_focus=true), however, it is not recognising the command after the install... Any ideas? This is the [workflow file](https://github.com/afonsojramos/discrakt/blob/fix-arm-linux/.github/workflows/build.yml#L54).

Context: I am only doing this because Rust was failing in the cross compilation for some reason [here](https://github.com/afonsojramos/discrakt/runs/5668230854?check_suite_focus=true). If you have any idea here it would be even better!
